// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm7QOWCOeUaeRquj4UbRqnIuTSKT4MJvk',
    appId: '1:355183523182:web:64debf16b91397b1247d7f',
    messagingSenderId: '355183523182',
    projectId: 'vendor-discover-7346a',
    authDomain: 'vendor-discover-7346a.firebaseapp.com',
    storageBucket: 'vendor-discover-7346a.firebasestorage.app',
    measurementId: 'G-T3YK6LT7MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW9XMVtYO0iFCiEM_R3wBwf6USvAkuWw8',
    appId: '1:355183523182:android:38a0c4a1a98b0a68247d7f',
    messagingSenderId: '355183523182',
    projectId: 'vendor-discover-7346a',
    storageBucket: 'vendor-discover-7346a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4jMgn1rkm8yZU7FJohELk79xcL8qWstY',
    appId: '1:355183523182:ios:f08da02b81306861247d7f',
    messagingSenderId: '355183523182',
    projectId: 'vendor-discover-7346a',
    storageBucket: 'vendor-discover-7346a.firebasestorage.app',
    iosBundleId: 'com.example.vendorsDiscover',
  );

}